name: Build

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    name: Build - ${{ matrix.job.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - { name: "x86_64",    wol_platform: "x86_64"  }
          - { name: "arm64-v8a", wol_platform: "aarch64" }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Get module property
        run: |
          MOD_VERSION=$(awk -F "=" '/version=/ {print $2}' module.prop)
          MOD_WOL_TAG=$(echo "${MOD_VERSION}" | cut -d "." -f 1-3)
          {
            echo "MOD_VERSION=${MOD_VERSION}"
            echo "MOD_WOL_TAG=${MOD_WOL_TAG}"
          } >> "${GITHUB_ENV}"

      - name: Download WOL
        run: |
          mkdir -p wol/bin
          curl -LO https://github.com/nashaofu/wol/releases/download/${{ env.MOD_WOL_TAG }}/wol-${{ matrix.job.wol_platform }}-unknown-linux-musl.zip
          unzip -jo wol-*.zip -d wol/bin

      - name: Append update json to module.prop
        run: |
          echo "updateJson=https://github.com/${{ github.repository }}/releases/latest/download/update-${{ matrix.job.name }}.json" >> module.prop

      - name: Package artifact
        run: |
          mkdir -p artifact
          cp -r META-INF wol artifact/
          cp LICENSE module.prop artifact/
          cp customize.sh service.sh uninstall.sh artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wol-${{ env.MOD_VERSION }}-${{ matrix.job.name }}
          path: artifact/
          if-no-files-found: error
