name: CI

on:
  workflow_call:
  push:
    branches: [master]
    tags: ["v*"]

jobs:
  build:
    name: Build - ${{ matrix.job.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - { name: "x86_64",    wol_platform: "x86_64"  }
          - { name: "arm64-v8a", wol_platform: "aarch64" }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Get WOL tag
        run: |
          echo "WOL_TAG=$(awk -F '=' '/version=/ {print $2}' module.prop | cut -d '.' -f 1-3)" >> $GITHUB_ENV

      - name: Download WOL
        uses: robinraju/release-downloader@v1
        with:
          repository: nashaofu/wol
          latest: false
          tag: ${{ env.WOL_TAG }}
          fileName: wol-${{ matrix.job.wol_platform }}*-musl.zip
          out-file-path: wol/bin
          tarBall: false
          zipBall: true
          extract: true

      - name: Package
        run: |
          mkdir -p build
          mv -f wol/bin/wol-* wol/bin/wol
          zip -9 -r buld/wol-${GITHUB_REF#refs/tags/}-${{ matrix.job.name }}.zip -x "*.git*" ".pre-commit-config.yaml" "build/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wol-${{ matrix.job.name }}-artifact
          path: build/*.zip
          if-no-files-found: error

      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            build/*.zip
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          generate_release_notes: true
